# Generated by Django 4.2.3 on 2023-07-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
    ]
